[project]
name = "emailwriter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.53.0",
    "pyperclip>=1.9.0",
    "python-dotenv>=1.0.1",
    "streamlit>=1.39.0",
    "watchdog>=5.0.3",
]
